
namespace FullerHelpers
{
    class DataFillers
    {
        private string[] FirstNames = { "Aaron", "Adam", "Adrian", "Alex", "Alexander", "Alexandra", "Alicia", "Alison", "Allison", "Amanda", "Amber", "Amy", "Andrea", "Andrew", "Angela", "Anna", "Anthony", "Antonio", "April", "Ashley", "Benjamin", "Bethany", "Blake", "Bradley", "Brandi", "Brandon", "Brandy", "Brent", "Brett", "Brian", "Brittany", "Brittney", "Bryan", "Caitlin", "Candice", "Carlos", "Carrie", "Casey", "Cassandra", "Catherine", "Chad", "Charles", "Chelsea", "Christina", "Christine", "Christopher", "Cody", "Corey", "Cory", "Courtney", "Craig", "Crystal", "Curtis", "Cynthia", "Dana", "Daniel", "Danielle", "David", "Derek", "Derrick", "Diana", "Dominique", "Donald", "Douglas", "Dustin", "Edward", "Elizabeth", "Emily", "Eric", "Erica", "Erik", "Erika", "Erin", "Evan", "Frank", "Gabriel", "Gary", "George", "Gregory", "Heather", "Holly", "Ian", "Jacob", "Jacqueline", "James", "Jamie", "Jared", "Jason", "Jeffery", "Jeffrey", "Jenna", "Jennifer", "Jeremy", "Jesse", "Jessica", "Joanna", "Joel", "John", "Jonathan", "Jordan", "Jose", "Joseph", "Joshua", "Juan", "Julia", "Julie", "Justin", "Kara", "Karen", "Katherine", "Kathleen", "Kathryn", "Katie", "Katrina", "Keith", "Kelly", "Kenneth", "Kevin", "Kimberly", "Kristen", "Kristin", "Kristina", "Krystal", "Kyle", "Larry", "Latoya", "Laura", "Lauren", "Leah", "Leslie", "Lindsay", "Lindsey", "Lisa", "Luis", "Marcus", "Margaret", "Maria", "Mark", "Mary", "Matthew", "Megan", "Meghan", "Melanie", "Melissa", "Michael", "Michelle", "Monica", "Natalie", "Natasha", "Nathan", "Nathaniel", "Nicholas", "Nichole", "Nicole", "Patricia", "Patrick", "Paul", "Peter", "Philip", "Phillip", "Rachael", "Rachel", "Raymond", "Rebecca", "Richard", "Robert", "Ronald", "Ryan", "Samantha", "Samuel", "Sara", "Sarah", "Scott", "Sean", "Shane", "Shannon", "Shawn", "Sheena", "Stacey", "Stacy", "Stephanie", "Stephen", "Steven", "Tara", "Thomas", "Tiffany", "Timothy", "Todd", "Travis", "Tyler", "Valerie", "Vanessa", "Veronica", "Victor", "Victoria", "Vincent", "Wesley", "Whitney", "William", "Zachary" };
        private string[] LastNames = { };
    }
}
